### ISSUE TITLE
Where's Mobile???

### ISSUE THREAD

**Issue by saymon-araujo** [zTrolly/computing-courses#1]
O mais importante o cara deixou de fora ;-;

**Comment by zTrolly** [comment]
Ta complicado viu, tenho que estudar Java e algum frameWork, Node e Js com algum frameWork. Quem sabe não começo com um React Native hein

**Comment by saymon-araujo** [comment]
Talvez onde estou trabalhando vão precisar de desenvolvedores em breve, se tiver afim de saber mais manda mensagem lá no whats.
